# Generated by Django 3.2.16 on 2022-12-27 16:19
from django.db import migrations


def forwards_func(apps, schema_editor):
    # Get model
    Courses = apps.get_model("mainapp", "Courses")
    # Create model's objects
    Courses.objects.create(
        pk=9,
        name="1С-программист",
        description="1C-программист помогает автоматизировать бизнес-процессы компании. Платформу «1С: Предприятие» используют для автоматизации процессов и решения учётных задач компании: бухгалтерских, кадровых, управленческих. Чтобы настроить её под функции бизнеса, нужны 1С-программисты.",
        description_as_markdown=True,
        cost="9500.00",
        cover="img/no_image.svg",
    )
    Courses.objects.create(
        pk=10,
        name="Проджект-менеджер",
        description="Он руководит проектом на всех этапах его жизненного цикла. Несёт ответственность за процессы и команду: определяет цели, следит за сроками, прогнозирует результаты. Главная задача — постоянно оптимизировать и улучшать IT-продукт.",
        cost="7500.00",
        cover="img/no_image.svg",
    )
    Courses.objects.create(
        pk=11,
        name="Мидл фронтенд-разработчик",
        description="Мидл frontend-разработчик вдумчиво выбирает технологии для реализации проекта и может аргументировать свой выбор. Уверенно чувствует себя в процессах командной разработки и самостоятельно решает комплексные задачи.",
        description_as_markdown=True,
        cost="1500.00",
        cover="img/no_image.svg",
    )


def reverse_func(apps, schema_editor):
    # Get model
    Courses = apps.get_model("mainapp", "Courses")
    # Delete objects
    Courses.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_data_migration"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
