# Generated by Django 3.2.16 on 2022-12-27 17:59

from django.db import migrations


def forwards_func(apps, schema_editor):
    # Get model
    Lesson = apps.get_model("mainapp", "Lesson")
    # Create model's objects
    Course = apps.get_model("mainapp", "Courses")
    Course9 = Course.objects.get(id=9)
    Lesson.objects.create(course=Course9, num=1, title="Lesson 1", description="Описание 1 урока")

    Lesson.objects.create(course=Course9, num=2, title="Lesson 2", description="Описание 2 урока")

    Lesson.objects.create(course=Course9, num=3, title="Lesson 3", description="Описание 3 урока")

    Lesson.objects.create(course=Course9, num=4, title="Lesson 4", description="Описание 4 урока")

    Lesson.objects.create(course=Course9, num=5, title="Lesson 5", description="Описание 5 урока")

    Lesson.objects.create(course=Course9, num=6, title="Lesson 6", description="Описание 6 урока")

    Lesson.objects.create(course=Course9, num=7, title="Lesson 7", description="Описание 7 урока")

    Lesson.objects.create(course=Course9, num=8, title="Lesson 8", description="Описание 8 урока")

    Course10 = Course.objects.get(id=10)
    Lesson.objects.create(course=Course10, num=1, title="Lesson 1", description="Описание 1 урока")

    Lesson.objects.create(course=Course10, num=2, title="Lesson 2", description="Описание 2 урока")

    Lesson.objects.create(course=Course10, num=3, title="Lesson 3", description="Описание 3 урока")

    Lesson.objects.create(course=Course10, num=4, title="Lesson 4", description="Описание 4 урока")

    Lesson.objects.create(course=Course10, num=5, title="Lesson 5", description="Описание 5 урока")

    Lesson.objects.create(course=Course10, num=6, title="Lesson 6", description="Описание 6 урока")

    Lesson.objects.create(course=Course10, num=7, title="Lesson 7", description="Описание 7 урока")

    Lesson.objects.create(course=Course10, num=8, title="Lesson 8", description="Описание 8 урока")


def reverse_func(apps, schema_editor):
    # Get model
    Lesson = apps.get_model("mainapp", "Lesson")
    # Delete objects
    Lesson.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_data_migration_courses"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
