# Generated by Django 3.2.16 on 2022-12-27 17:59

from django.db import migrations


def forwards_func(apps, schema_editor):
    # Get model
    Teacher = apps.get_model("mainapp", "CourseTeachers")
    # Create model's objects
    Courses = apps.get_model("mainapp", "Courses")
    teacher1 = Teacher.objects.create(name_first="Иван", name_second="Сидоров", day_birth="1984-02-23")
    teacher1.course.set([Courses.objects.get(id=9), Courses.objects.get(id=10)])
    teacher1.save()

    teacher2 = Teacher.objects.create(name_first="Петр", name_second="Иванишко", day_birth="1981-12-03")
    teacher2.course.set([Courses.objects.get(id=10), Courses.objects.get(id=11)])
    teacher2.save()


def reverse_func(apps, schema_editor):
    # Get model
    Teacher = apps.get_model("mainapp", "CourseTeachers")
    # Delete objects
    Teacher.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0007_data_migration_lessons"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
