# Generated by Django 3.2.16 on 2023-01-16 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0009_auto_20230116_1833"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courseteachers",
            options={"verbose_name": "Teacher", "verbose_name_plural": "Teachers"},
        ),
    ]
