# Generated by Django 3.2.16 on 2023-01-20 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0011_coursefeedback"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courses",
            options={"ordering": ("created",), "verbose_name": "Courses", "verbose_name_plural": "Courses"},
        ),
    ]
