# Generated by Django 3.2.16 on 2023-01-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0002_alter_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="login",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
